config/routes.rb
Rails.application.routes.draw do
  

  resources :counters

  resources :shops

  resources :workouts

  root 'workouts#homepage'

  get 'dashboard/index'

  get 'workouts/homepage' => 'workouts#homepage'

  get 'counters' => 'counters#show'

  devise_for :users , :controller => {:registrations => "registrations"}

  resources :devices

  resources :performeds

  resources :involvements

  resources :programs

  resources :exercises

  resources :profiles do
    collection do
      post 'select_program'
      get 'perWeek'
      get 'pishraft'
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #after_save :do_go_home

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @program = Program.all
    @my_exercises = current_user.exercises.all
    @my_profile = current_user.profile
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end


  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    @profile.user_id = current_user.id
    if params[:gender_male] == "on"
      @profile.gender = "مرد"
    elsif params[:gender_female] == "on"
      @profile.gender = "زن"
    end

    # byebug

    respond_to do |format|
      if @profile.save
        format.html { redirect_to :controller => 'workouts' , :action => 'homepage' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  #hooman/jadval miani
  def select_program
    @exercise = Exercise.new
    @exercise.program_id = params[:program_id]
    @exercise.user_id = current_user.id
    @exercise.save

    redirect_to profile_path(current_user.profile.id)

  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def perWeek
  end
  def pishraft
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :email, :age, :gender, :height, :weight, :user_id)
    end

    def do_go_homed
          redirect_to :controller => 'workouts' , :action => 'show' , :id => current_user.id
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.2.0
Version: 3.3.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest (the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>FitNet | Sign-Up</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Fonts START -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">
  <!-- Fonts END -->

  <!-- Global styles START -->          
  <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="/assets/global/plugins/bootstrap/css/bootstrap-rtl.min.css" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="/assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
  <link href="/assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel-rtl.css" rel="stylesheet">
  <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="/assets/global/css/components-rtl.css" rel="stylesheet">
  <link href="/assets/frontend/layout/css/style.css" rel="stylesheet">
  <link href="/assets/frontend/pages/css/style-shop.css" rel="stylesheet" type="text/css">
  <link href="/assets/frontend/layout/css/style-responsive.css" rel="stylesheet">
  <link href="/assets/frontend/layout/css/themes/red.css" rel="stylesheet" id="style-color">
  <link href="/assets/frontend/layout/css/custom.css" rel="stylesheet">
  <!-- Theme styles END -->

  <link href="/assets/frontend/layout/css/profileCss.css" rel="stylesheet" type="text/css">
</head>


    
    <div class="main">
      <div class="container">
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
          <!-- BEGIN SIDEBAR -->
          <!-- END SIDEBAR -->

          <!-- BEGIN CONTENT -->
          <div class="col-md-9 col-sm-7">
           





            <div class="content-form-page">

            <%= form_for @profile ,:html => {:class => "form-horizontal form-without-legend" } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="well">
  <h2> ایجاد پروفایل </h2>
   
   <div class="form-group">
      <%= f.label :نام ,class:'col-lg-2 control-label ' , style:'float:right;'%> 

          <div class="col-lg-8">
      <%= f.text_field :firstname ,class:'form-control' , style:'margin-top:19px' %>
    </div>
  </div> 

  <div class="form-group">
    <label class="col-lg-2 control-label" , style="float:right;" >نام خانوادگی</label><br>
      <div class="col-lg-8">
    <%= f.text_field :lastname ,class:'form-control' %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :ایمیل , class:'col-lg-2 control-label' , style:'float:right;'%> <span class="require">*</span><br>
    <div class="col-lg-8">
    <%= f.text_field :email , class:'form-control'  %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :سن , class:'col-lg-2 control-label' , style:'float:right;'%> <span class="require">*</span><br>
    <div class="col-lg-8">
    <%= f.number_field :age ,class:'form-control mytest' ,style:'padding-top:0px; padding-bottom:0px;' %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :جنسیت ,class:'col-lg-2 control-label' , style:'float:right;'%><br>
    <div class="col-lg-8 checkbox-list">
      <label>
        <input type="checkbox" name="gender_male"> مرد
      </label>
      <label>
        <input type="checkbox" name="gender_female"> زن
      </label>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :قد ,class:'col-lg-2 control-label' , style:'float:right;'%><span class="require">*</span><br>
      <div class="col-lg-8">
    <%= f.number_field :height,class:'form-control',style:'padding-top:0px; padding-bottom:0px;' %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :وزن ,class:'col-lg-2 control-label' , style:'float:right;' %> <span class="require">*</span><br>
    <div class="col-lg-8">
    <%= f.number_field :weight ,class:'form-control',style:'padding-top:0px; padding-bottom:0px;' %>
      </div>
  </div>
  <div class="form-group">
    <% f.label :user_id %>
    <% f.number_field :user_id %>
  </div>
  <div class="row">
    <div class="col-lg-8 col-md-offset-2 padding-left-0 padding-top-20">
      <button class="btn btn-primary" type="submit"> ذخیره</button>
    </div>
  </div>

  </div>

<% end %>

             
            </div>
          </div> 
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
      </div>
    </div>

    <!-- BEGIN BRANDS -->
    <!-- END BRANDS -->

    <!-- BEGIN STEPS -->
    <!-- END STEPS -->

    <!-- BEGIN PRE-FOOTER -->
    <!-- END PRE-FOOTER -->

    <!-- BEGIN FOOTER -->
    <!-- END FOOTER -->

    <!-- BEGIN fast view of a product -->
    <!--
    


    <!-- END fast view of a product -->

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="../../assets/global/plugins/respond.min.js"></script>  
    <![endif]-->  
    <script src="../../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="../../assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <script src="../../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>      
    <script src="../../assets/frontend/layout/scripts/back-to-top.js" type="text/javascript"></script>
    <script src="../../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="../../assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="../../assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel-rtl.js" type="text/javascript"></script><!-- slider for products -->
    <script src='../../assets/global/plugins/zoom/jquery.zoom.min.js' type="text/javascript"></script><!-- product zoom -->
    <script src="../../assets/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script><!-- Quantity -->
    <script src="../../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>

    <script src="../../assets/frontend/layout/scripts/layout.js" type="text/javascript"></script>
     <!-- <script type="text/javascript">
        jQuery(document).ready(function() {
            Layout.init();    
            Layout.initOWL();
            Layout.initTwitter();
            Layout.initImageZoom();
            Layout.initTouchspin();
            Layout.initUniform();
        });
    </script> -->
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

app/views/profiles/edit.html.erb
<!-- <h1>Editing Profile</h1> -->

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>firstname</th>
      <th>lastname</th>
      <th>email</th>
      <th>Age</th>
      <th>gender</th>
      <th>Height</th>
      <th>Weight</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.email %></td>
        <td><%= profile.age %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.height %></td>
        <td><%= profile.weight %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/perWeek.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <title>نمودار</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />




<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/adapters/standalone-framework.js"></script>
   

</head>
<body>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<script>
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'تعداد حرکت هر روز'
        },
        xAxis: {
            categories: [
                '1',
                '2',
                '3',
                '4',
                '5',
                '6',
                '7',
                '8',
                '9',
                '10',
                '11',
                '13',
                '14',
                '15',
                '16',
                '17',
                '18',
                '19',
                '20',
                '21',
                '22',
                '23',
                '24',
                '25',
                '26',
                '27',
                '28',
                '29',
                '30',
                '31'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'تعداد حرکت '
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{}: </td>' +
                '<td style="padding:0"><b>{point.y} </b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            
            data: [11,13,1,5,6,77,3,1,3,46,3,66,22,44,55,1,23,54,67,75,75,13,13,43,1,22,3,61,<%=Counter.find_by_id(1).count%>,0]

        }]
    });
});
</script>
</body>
</html>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>





<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>


     <link rel='stylesheet' href='/assets/fullcalendar.css' /> 
     <link rel='stylesheet' href='/assets/cal.css' /> 
    <!--<script src='assfullcal/lib/jquery.min.js'></script> -->
     <script src='/assets/moment.min.js'></script> 
     <script src='/assets/fullcalendar.js'></script> 

<meta charset="utf-8"/>
<title>FitNet | New User Profile</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/bootstrap/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin/pages/css/profile-rtl.css" rel="stylesheet" type="text/css"/>
<link href="/assets/admin/pages/css/tasks-rtl.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="/assets/global/css/components-md-rtl.css" id="style_components" rel="stylesheet" type="text/css">
<link href="/assets/global/css/plugins-md-rtl.css" rel="stylesheet" type="text/css">
<link href="/assets/admin/layout3/css/layout-rtl.css" rel="stylesheet" type="text/css">
<link href="/assets/admin/layout3/css/themes/default-rtl.css" rel="stylesheet" type="text/css" id="style_color">
<link href="/assets/admin/layout3/css/custom-rtl.css" rel="stylesheet" type="text/css">
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
<style>
    .page-content {
        background-color: rgb(135, 135, 128);
    }

</style>

 <link href="/assets/profileCss2.css" rel="stylesheet" type="text/css">
</head>

<body background="/assets/gray2.jpg">
  <!-- END PAGE HEAD -->
  <!-- BEGIN PAGE CONTENT -->
  <div class="page-content" >
    <div class="container">
      <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
              <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
               Widget settings form goes here
            </div>
            <div class="modal-footer">
              <button type="button" class="btn blue">Save changes</button>
              <button type="button" class="btn default" data-dismiss="modal">Close</button>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <!-- BEGIN PAGE BREADCRUMB -->
      <!-- END PAGE BREADCRUMB -->
      <!-- BEGIN PAGE CONTENT INNER -->
      <div class="row margin-top-10">
        <div class="col-md-12">
          <!-- BEGIN PROFILE SIDEBAR -->
          <div class="profile-sidebar" style="width: 250px;">
            <!-- PORTLET MAIN -->
            <div class="portlet light profile-sidebar-portlet sizeTwo">
              <!-- SIDEBAR USERPIC -->
              <div class="profile-userpic">
                <img src="../../assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
              </div>
              <!-- END SIDEBAR USERPIC -->
              <!-- SIDEBAR USER TITLE -->
              <div class="profile-usertitle">
                <div class="profile-usertitle-name">
                  <%= @my_profile.firstname %> <%= @my_profile.lastname %>
                </div>
            
              </div>
              <!-- END SIDEBAR USER TITLE -->
              <!-- SIDEBAR BUTTONS -->
              <div class="profile-userbuttons">

                <%= form_tag edit_profile_path do %>
                <%= link_to edit_profile_path(@my_profile) do%>
                  <div class ="btn btn-danger" >
                  ویرایش اطلاعات
                  </div>
                <% end %>
                <% end %>
                
                <!-- <button type="button" class="btn btn-circle green-haze btn-sm">ویرایش</button> -->
              </div>
              <!-- END SIDEBAR BUTTONS -->
              <!-- SIDEBAR MENU -->
              <div class="profile-usermenu">
                <ul class="nav">
                  <li class="active">
                                        <a style="cursor:default">قد : <%= @my_profile.height %></a>
                                        
                  </li>
                  <li>
                                        <a style="cursor:default">وزن : <%= @my_profile.weight %></a>
                  </li>
                  <li>
                                        <a style="cursor:default">جنسیت : مرد</a>
                  </li>
                  <li>
                                        <a style="cursor:default">سن :<%= @my_profile.age %></a>
                  </li>
                </ul>
              </div>
              <!-- END MENU -->
            </div>
            <!-- END PORTLET MAIN --> 
          </div>
          <!-- END BEGIN PROFILE SIDEBAR -->
          <!-- BEGIN PROFILE CONTENT -->
          <div class="profile-content">
            <div class="row">
              <div class="col-md-6">
                <!-- BEGIN PORTLET -->
                <div class="portlet light sizeCon">
                                    <div id="title-light1">
                                        نمودار پیشرفت
                                    </div>
                                    <div class="commentOncharts">
                                       دراین قسمت شما میتوانید نمودار های مربوط به پیشرفت خود را مشاهده کنید 
                                    </div>
                                     <div>
                                     <%= link_to 'نمودار رشد', perWeek_profiles_path , method: :get%>  
                                    <img src="/assets/line2.jpg" class="img-responsive nemoodar1" height="100" width="200">   
                                     </div> 
                                     <div>
                                       <%= link_to 'نمودار پیشرفت', pishraft_profiles_path , method: :get%>
                                    
                                    <img src="/assets/line1.jpg" class="img-responsive nemoodar2"  height="100" width="200">
                                     </div>
                                     
                </div>
                <!-- END PORTLET -->
              </div>
              <div class="col-md-6">
                <!-- BEGIN PORTLET -->
                                <div class="portlet light contains_cal">
                                    <div id='calendar'></div>
                                </div>
                                
                                <script>
                                    $(document).ready(function () {

                                        // page is now ready, initialize the calendar...

                                        $('#calendar').fullCalendar({
                                            // put your options and callbacks here
                                        })

                                    });
                                    $('#calendar').fullCalendar({
                                        dayClick: function () {
                                            alert('a day has been clicked!');
                                        }
                                    });
                                </script>
                <!-- END PORTLET -->
              </div>
            </div>
                       
            <div class="row">
              <div class="col-md-6">
                <!-- BEGIN PORTLET -->
                <div class="portlet light">
                  <div class="portlet-title">
                  <p style="margin-right:128px;font-size:26px;color:red;"> برنامه های من </p>
                    <% @my_exercises.each do |exer| %>
                      <%= link_to({:controller=> 'programs' , action: 'show' , :id => exer.program.id}) do %>
                        <p> <%= exer.program.name %></p>
                      <% end %> 
                    <%end%>          
                      <img class="img-responsive aks" src="/assets/program1.png" style="width:100;height:200;">
                  </div>
                </div>
                <!-- END PORTLET -->
              </div>
            </div>
          </div>
          <!-- END PROFILE CONTENT -->
        </div>
      </div>
      <!-- END PAGE CONTENT INNER -->
    </div>
  </div>
  <!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->
<!-- BEGIN PRE-FOOTER -->

<div class="scroll-to-top">
  <i class="icon-arrow-up"></i>
</div>

<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="../../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="../../assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="../../assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="../../assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="../../assets/admin/layout3/scripts/layout.js" type="text/javascript"></script>
<script src="../../assets/admin/layout3/scripts/demo.js" type="text/javascript"></script>
<script src="../../assets/admin/pages/scripts/profile.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {       
    // initiate layout and plugins
    Metronic.init(); // init metronic core components
  Layout.init(); // init current layout
  Demo.init(); // init demo features\
  Profile.init(); // init page demo
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>