config/routes.rb
Rails.application.routes.draw do
  

  resources :counters

  resources :shops

  resources :workouts

  root 'workouts#homepage'

  get 'dashboard/index'

  get 'workouts/homepage' => 'workouts#homepage'

  get 'counters' => 'counters#show'

  devise_for :users , :controller => {:registrations => "registrations"}

  resources :devices

  resources :performeds

  resources :involvements

  resources :programs

  resources :exercises

  resources :profiles do
    collection do
      post 'select_program'
      get 'perWeek'
      get 'pishraft'
    end
  end

end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :shop
		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :user
	belongs_to :program
end

app/models/involvement.rb
class Involvement < ActiveRecord::Base

	belongs_to :program
	belongs_to :workout
end

app/models/performed.rb
class Performed < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user

end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :exercises
	has_many :involvements
	has_many :workouts , :through => :involvements
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	  has_many :devices
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  has_one :profile
  has_many :exercises

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ActiveRecord::Base

	has_many :involvements
	has_many :perforemeds 
	has_many :programs , :through => :involvements

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :price, :description, :workout_id ,:avatar )
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
    @devices = Device.all
  
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:device_id)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json


  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @devices_name = []
    @devices = Device.all
    @devices.each do |d|
      @devices_name << d.name
    end
  end

  # GET /workouts/new
  def new
    @devices_name = []
    @workout = Workout.new
    @devices = Device.all
    @devices.each do |d|
      @devices_name << d.name
    end
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    

    respond_to do |format|
      if @workout.save

        @performed = Performed.new
        @performed.workout_id = @workout.id
        @performed.device_id = Device.find_by_name(params[:device_name]).id
        @performed.save
        # byebug
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @workout }
      else
        # byebug
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:name, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/helpers/performeds_helper.rb
module PerformedsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->

        <link rel="stylesheet" href="/assets/css2/style.css">
</head>
    <body>

        <div class="register-container container " style="margin-right:-6%;margin-top:10%;" >
            <div class="row">

                </div>
                
                <div class="register span6">
                <%= form_for(@workout) do |f| %>
                    <form action="" method="post">
                        <h2>ایجاد  <span class="red"><strong> تمرین </strong></span></h2>
                        <label for="firstname">نام تمرین</label>
    					<%= f.text_field :name ,class:'inp-text' ,style:" width: 40%;"%><br>
                    <!--     <input type="text" id="firstname" name="firstname" placeholder="enter your first name...">  -->
                        <label for="lastname"> نام دستگاه</label>
                        <%= select_tag :device_name, options_for_select(@devices_name) ,style:" width: 40%;" %><br><br>
                       <!--  <input type="text" id="lastname" name="lastname" placeholder="enter your first name..."> -->
                        <label for="username" style="margin-right:13%;">عکس</label>
    					<%= f.file_field :avatar , class:'inp-text',style:" width: 40%; margin-right: 37%;" %><br><br>
                        <!-- <input type="text" id="username" name="username" placeholder="choose a username..."> -->

<!--                    <input type="text" id="email" name="email" placeholder="enter your email..."> -->
        
                      <div class="clearfix form-actions" style="margin-right:25%;">
                      <div class="col-md-offset-3 col-md-9">
                        <%= content_tag :button, :type => :submit, :class => "btn btn-danger" ,style:'padding-left:11%;' do %>
                        <i class="icon-ok bigger-110" ></i>
                        <%=t :ذخیره%>
                        <% end %>
                      </div>
                    </div>
                      
                    </form>
                <%end%>
                </div>
                
            </div>
        </div>


        <script src="/assets/js2/jquery-1.8.2.min.js"></script>
        <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/assets/js2/jquery.backstretch.min.js"></script>
        <script src="/assets/js2/scripts.js"></script>

    </body>

</html>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/homepage.html.erb
<!DOCTYPE html>
<meta charset="UTF-8">
<html>
<head>
    <meta charset="UTF-8">
    <title>Fit Net</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <link rel="stylesheet" href="/assets/stylesheets/homeCssNew.css" />

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>
        $(function () {
            var pull = $('#pull');
            menu = $('nav ul');
            menuHeight = menu.height();

            $(pull).on('click', function (e) {
                e.preventDefault();
                menu.slideToggle();
            });

            $(window).resize(function () {
                var w = $(window).width();
                if (w > 320 && menu.is(':hidden')) {
                    menu.removeAttr('style');
                }
            });
        });
    </script>

</head>
<body>
<!-- 
    <header>
        <div id="onMenu">
            <img class="img-responsive logo" src="pic/logo.png" alt="haeder" width="200" height="22">
            <div class="shoar"></div>
            <a href="#" class="shop"></a>
            <a href="#" class="login"></a>
            <a href="#" class="help"></a>
        </div>
        <div id="menu">
            <a href="#" class="m1"></a>

            <a href="#" class="m2"></a>

            <a href="#" class="m3"></a>

            <a href="#" class="m4"></a>

            <a href="#" class="m5"></a>

            <a href="#" class="m6"></a>
        </div>
    </header>

 -->    
    <div id="slideShow">
        <div class="btn">
            <div class="inner">خرید محصول</div>
        </div>

        <div class="btn2">
            <div class="inner">فیت نت چیست</div>
        </div>
    </div>

    <div id="afterSlideShow">
        <div class="txtParent">
            <a href="#" class="txtRight">اصول ورزش در خانه</a>
            <a href="#" class="txtLeft">ورزش های کششی</a>
        </div>
        <div class="txtParent">
        <a href="#" class="txtRight">وسایل ورزشی مناسب</a>

        <a href="#" class="txtLeft">برنامه ورزشی</a>
        </div>
        <div class="txtParent">
        <a href="#" class="txtRight">تناسب اندام</a>
        <a href="#" class="txtLeft">کاهش وزن و سلامتی</a>
        </div>
    </div>

    <article>
        <section class="group">
            <div class="col-md-6 col-sm-6 col-xs-12 item1">

            </div>
            
            <div class="col-md-6 col-sm-6 col-xs-12 item2">
                <div class="btn">
                    <div class="inner">تناسب اندام</div>
                </div>

            </div>
            
            <div class="col-md-6 col-sm-6 col-xs-12 item3">
                <div class="btn">
                    <div class="inner">خرید محصول</div>
                </div>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-12 item4">

            </div>


        </section>
    </article>

    <!-- <footer>
        <div class="email">
            <button type="button" class="btn btn-danger">ثبت</button>
            <input type="email" class="form-control" id="email" placeholder="رایان نامه">
            <label class="txt">برای آگاهی از آخرین محصولات و برنامه ها ایمیل خود را ثبت کنید</label>
        </div>

        <div class="contactUs">
                <a class="twitter" href="#"></a>
                <a class="facebook" href="#"></a>
                <a class="instagram" href="#"></a>
            <div class="contactInfo">
            </div>
        </div>

        <div class="copyWrite">
            <img class="img-responsive logo" src="pic/logo.png" alt="haeder" width="200" height="22">
            <p class="cop">این سایت تحت نظارت سازمان بین المللی رژیم غذایی سوئد ساخته شده و تمامی حقوق آن محفوظ است</p>
        </div>
    </footer> -->
</body>
</html>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="well text-center" id="program-show-main-div">

<div class="row">
<h1>Listing Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= workout.avatar %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>
</div>
</div>

app/views/workouts/new.html.erb
<%= render 'form' %>

app/views/workouts/show.html.erb
<div class="well text-center" id="program-show-main-div">

<div class="row">

<p id="notice"><%= notice %></p>

<p>
  <strong>نام:</strong>
  <%= @workout.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%=image_tag @workout.avatar.url %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> 
</div>
</div>