config/routes.rb
Rails.application.routes.draw do
  

  resources :counters

  resources :shops

  resources :workouts

  root 'workouts#homepage'

  get 'dashboard/index'

  get 'workouts/homepage' => 'workouts#homepage'

  get 'counters' => 'counters#show'

  devise_for :users , :controller => {:registrations => "registrations"}

  resources :devices

  resources :performeds

  resources :involvements

  resources :programs

  resources :exercises

  resources :profiles do
    collection do
      post 'select_program'
      get 'perWeek'
      get 'pishraft'
    end
  end

end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :shop
		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :user
	belongs_to :program
end

app/models/involvement.rb
class Involvement < ActiveRecord::Base

	belongs_to :program
	belongs_to :workout
end

app/models/performed.rb
class Performed < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user

end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :exercises
	has_many :involvements
	has_many :workouts , :through => :involvements
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	  has_many :devices
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  has_one :profile
  has_many :exercises

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ActiveRecord::Base

	has_many :involvements
	has_many :perforemeds 
	has_many :programs , :through => :involvements

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy]

  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
     @counter = Counter.find(params[:id])
     @counter.count = @counter.count + 1
     #@counter.count =0
     @counter.save
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render :show, status: :created, location: @counter }
      else
        format.html { render :new }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { render :show, status: :ok, location: @counter }
      else
        format.html { render :edit }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url, notice: 'Counter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.require(:counter).permit(:count)
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :price, :description, :workout_id ,:avatar )
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
    @devices = Device.all
  
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:device_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/helpers/performeds_helper.rb
module PerformedsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/counters/_form.html.erb
<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing Counter</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Counters</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td><%= counter.count %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/new.html.erb
<h1>New Counter</h1>

<%= render 'form' %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @counter.count %>
</p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/devices/_form.html.erb
  <!-- <fieldset>
    <h2 class="fs-title"> Create your account </h2>
    <h3 class="fs-subtitle">This is step 1</h3>
    <input type="text" name="email" placeholder="Email" />
    <input type="password" name="pass" placeholder="Password" />
    <input type="password" name="cpass" placeholder="Confirm Password" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Social Profiles</h2>
    <h3 class="fs-subtitle">Your presence on the social network</h3>
    <input type="text" name="twitter" placeholder="Twitter" />
    <input type="text" name="facebook" placeholder="Facebook" />
    <input type="text" name="gplus" placeholder="Google Plus" />
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Personal Details</h2>
    <h3 class="fs-subtitle">We will never sell it</h3>
    <input type="text" name="fname" placeholder="First Name" />
    <input type="text" name="lname" placeholder="Last Name" />
    <input type="text" name="phone" placeholder="Phone" />
    <textarea name="address" placeholder="Address"></textarea>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" />
  </fieldset> -->













<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <title>Fullscreen Responsive Register Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->

        <link rel="stylesheet" href="/assets/css2/style.css">
</head>
    <body>

        <div class="register-container container " style="margin-right:-6%;margin-top:10%;" >
            <div class="row">

                </div>
                
                <div class="register span6">
                <%= form_for(@device) do |f| %>
                    <form action="" method="post">
                        <h2>ایجاد  <span class="red"><strong>دستگاه</strong></span></h2>
                        <label for="firstname">نام دستگاه</label>
                        <%= f.text_field :name ,class:'inp-text' ,style:" width: 40%;"%><br>
                    <!--     <input type="text" id="firstname" name="firstname" placeholder="enter your first name...">  -->
                        <label for="lastname">قیمت</label>
                        <%= f.number_field :price ,class:'inp-text' ,style:" width: 40%;margin-right:6%;"%><br>
                       <!--  <input type="text" id="lastname" name="lastname" placeholder="enter your first name..."> -->
                        <label for="username">عکس</label>
                        <%= f.file_field :avatar , class:'inp-text',style:" width: 40%; margin-right: 30%;" %><br>
                        <!-- <input type="text" id="username" name="username" placeholder="choose a username..."> -->
                        <label for="email">توضیحات</label>
                        <%= f.text_field :description ,class:'inp-text' , style: 'width:389px; height:246px;'%>
<!--                    <input type="text" id="email" name="email" placeholder="enter your email..."> -->
        
                      <div class="clearfix form-actions" style="margin-right:25%;">
                      <div class="col-md-offset-3 col-md-9">
                        <%= content_tag :button, :type => :submit, :class => "btn btn-danger" ,style:'padding-left:11%;' do %>
                        <i class="icon-ok bigger-110" ></i>
                        <%=t :ذخیره%>
                        <% end %>
                      </div>
                    </div>
                      
                    </form>
                <%end%>
                </div>
                
            </div>
        </div>


        <script src="/assets/js2/jquery-1.8.2.min.js"></script>
        <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/assets/js2/jquery.backstretch.min.js"></script>
        <script src="/assets/js2/scripts.js"></script>

    </body>

</html>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Workout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.price %></td>
        <td><%= device.description %></td>
        <td><%= device.workout_id %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<%= render 'form' %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>نام دستگاه:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>ثیمت:</strong>
  <%= @device.price %>
</p>

<p>
  <strong>توضیحات:</strong>
  <%= @device.description %>
</p>

<p>
  <strong>تمرین:</strong>
  <%= @device.workout_id %>
</p>
<div style="height:100px; width:100px;">
  <strong>Avatar:</strong>
  <%=image_tag @device.avatar.url %>
</div>


<%= link_to 'Edit', edit_device_path(@device) %> |

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.number_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/assets/css/reset.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/assets/css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/assets/css/zerogrid.css" type="text/css" media="all">
    <link rel="stylesheet" href="/assets/css/responsive.css" type="text/css" media="all">
    <script src="/assets/js/jquery-1.6.2.min.js" type="text/javascript"></script>
    <script src="/assets/js/Vegur_300.font.js" type="text/javascript"></script>
    <script src="/assets/js/Vegur_400.font.js" type="text/javascript"></script> 
    <script src="/assets/js/FF-cash.js" type="text/javascript"></script>     
    <script type="text/javascript" src="/assets/js/css3-mediaqueries.js"></script>   
    <!--[if lt IE 7]>
        <div style=' clear: both; text-align:center; position: relative;'>
            <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0"  alt="" /></a>
        </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <script type="text/javascript" src="js/html5.js"></script>
        <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen">
    <![endif]-->
</head>
<body id="page3" style="background-color:white;">

    <div class="bg">
        <section id="content">
            <div class="main" style="background-image: url(/assets/gray2.jpg);background-repeat: no-repeat;">
                <div class="zerogrid">
                    <div class="row">
                        <article class="col-full">
                            <h3 class="p2" style="margin-top:5%;">فروشگاه</h3>
                            <div class="wrapper p4">
                                <% @devices.each do |dev| %>
                                <div class="col-1-3"><div class="wrap-col">
                                    <div class="wrapper p2">
                                        <figure class="border fleft"><img src="/assets/d1.jpg" alt="" /></figure>
                                    </div>
                                    <h6 class="prev-indent-bot"><a class="link" style="margin-right:45%;font-size:24px;color:white;" href="#"><%= dev.name %></a></h6>
                                    <h6 class="prev-indent-bot"><a class="link" style="margin-right:36%;font-size:24px;color:white;" href="#">قیمت: <%= dev.price %> ریال</a></h6>
                                    <p class="indent-bot"><%= dev.description %></p>
                                    <%= submit_tag 'خرید' , :class => "button" , style:'margin-right:36%;width:28%;' %>

                                </div></div>
                                <%end%>


                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @shop.device_id %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>