config/routes.rb
Rails.application.routes.draw do
  

  resources :counters

  resources :shops

  resources :workouts

  root 'workouts#homepage'

  get 'dashboard/index'

  get 'workouts/homepage' => 'workouts#homepage'

  get 'counters' => 'counters#show'

  devise_for :users , :controller => {:registrations => "registrations"}

  resources :devices

  resources :performeds

  resources :involvements

  resources :programs

  resources :exercises

  resources :profiles do
    collection do
      post 'select_program'
      get 'perWeek'
      get 'pishraft'
    end
  end

end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :shop
		has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :user
	belongs_to :program
end

app/models/involvement.rb
class Involvement < ActiveRecord::Base

	belongs_to :program
	belongs_to :workout
end

app/models/performed.rb
class Performed < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user

end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :exercises
	has_many :involvements
	has_many :workouts , :through => :involvements
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	  has_many :devices
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  has_one :profile
  has_many :exercises

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ActiveRecord::Base

	has_many :involvements
	has_many :perforemeds 
	has_many :programs , :through => :involvements

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/helpers/performeds_helper.rb
module PerformedsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitnet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- baraye login -->


    <!-- Latest compiled and minified CSS -->
  <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- jQuery library -->
  <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>

    <!-- Latest compiled JavaScript -->
  <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- baraye homepage -->
      <link rel="stylesheet" href="/assets/homeCssNew.css" /> 
  <%= csrf_meta_tags %>
</head>
<body>

<!-- ghesmati header k gharar ast hame ja tekrar shavad! -->

        <header class="">
        <div id="onMenu">
            <img class="img-responsive logo" src="/assets/logo.png" alt="haeder" width="200" >
            <div class="shoar"> <img class="img-responsive logo" src="/assets/shoar.png">  </div>
            <a href="#" class="shop"></a>
            <% if ! current_user.nil? %>
              <%= link_to  'خروج' , destroy_user_session_path , class: 'signout' ,style:'margin-left:100%;', method: :delete %>
            <% end %>

            <% if current_user.nil? %>
              <%= link_to "", new_user_session_path , class: 'loginmenu'%>
            <%end%>
            <a href="#" class="help"></a>
        </div>
        <div id="menu">
            <%= link_to new_user_registration_path  , class: 'm' do %>
              <p>
                ثبت نام
              </p>
            <% end %>

            <!-- <a href="#" class="m2"> <img class="img-responsive logo" src="/assets/2.png"> </a>

            <a href="#" class="m3"> <img class="img-responsive logo" src="/assets/3.png">  </a>

            <a href="#" class="m4"> <img class="img-responsive logo" src="/assets/4.png"> </a>

            <a href="#" class="m5"> <img class="img-responsive logo" src="/assets/5.png"> </a>

            <a href="#" class="m6"> <img class="img-responsive logo" src="/assets/6.png"> </a> -->
            <% if not current_user.nil? and not current_user.profile.nil?%> 
              <% if current_user.profile.role=="admin" %>
              <%= link_to new_program_path(current_user.profile) , class: 'm' do %>
               <p>
                 برنامه جدید
              </p>
              <% end %>
            
             <% else %>
             <a href="#" class="m"> 
                <p>
                  برنامه غذایی
                </p>
              </a>
            <% end %>
          <% end %>

            <%= link_to   root_url  , class: 'm' do %>
               <p>
                خانه
              </p>
            <% end %>
            
            <% if not current_user.nil? and not current_user.profile.nil?%>

            <% if current_user.profile.role=="admin" %>
              <%= link_to new_workout_path(current_user.profile) , class: 'm' do %>
               <p>
                تمرین
              </p>
              <% end %>

              <%= link_to new_device_path(current_user.profile) , class: 'm' do %>
               <p>
                دستگاه
              </p>
              <% end %>

            <% else %>
              <%= link_to profile_path(current_user.profile)  , class: 'm' do %>
               <p>
                پروفایل
              </p>
              <% end %>
            <% end %>

            <% end %>
            

            <!-- <a href="#" class="m"> 
              <p>
                Profile
              </p>
            </a> -->
            <%= link_to shops_path  , class: 'm' do %>
              <p>
                فروشگاه
              </p>
            <%end%>


           <%= link_to programs_path  , class: 'm' do %>
              <p>
                برنامه های ورزشی
              </p>
            </a>
           <% end %>
            
        </div>
    </header>

 <% if notice.present? %>
  <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
       <p class="alert"><%= alert %></p>
       <% end %>

       <div style="min-height:850px;margin-top:86px">
           <%= yield %>

       </div>


  <!-- ghesmate footer k gharar ast dar hame ja bashad -->
<%if not (params[:controller] == 'programs' and (params[:action] == 'new' or params[:action] == 'edit')) or (params[:controller] == 'workouts' and (params[:action] == 'new' or params[:action] == 'edit')) or (params[:controller] == 'devices' and (params[:action] == 'new' or params[:action] == 'edit'))%>
<div class="navbar navbar-default navbar-static-bottom" style="margin:0%;padding: 0;border: 0">
    
    <footer class="navbar " style="margin:0%;padding: 0;border: 0">
    <div style="">
        <div class="email" style="padding-top: 15px;">
            <button type="button" class="btn btn-danger">ثبت</button>
            <input type="email" class="form-control" id="email" placeholder="رایان نامه">
            <label class="txt">برای آگاهی از آخرین محصولات و برنامه ها ایمیل خود را ثبت کنید</label>
        </div>

        <div class="contactUs">
                <a class="twitter" href="#"></a>
                <a class="facebook" href="#"></a>
                <a class="instagram" href="#"></a>
            <div class="contactInfo">
            </div>
        </div>

        <div class="copyWrite">
            <img class="img-responsive logo" src="/assets/logo.png" alt="haeder" width="200" height="22">
            <p class="cop">این سایت تحت نظارت سازمان بین المللی رژیم غذایی سوئد ساخته شده و تمامی حقوق آن محفوظ است</p>
        </div>
    </div>
    </footer>

</div>
	<%end%>
</body>
</html>